import {  Inter, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  fontWeight: ["400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  fontWeight: ["400", "500", "600", "700", "800", "900"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${outfit.variable} ${inter.variable} h-full antialiased`}
    >
      <body className={`${inter.className} ${outfit.variable} min-h-full flex flex-col`}>
        <Navbar />
        <div className="bg-[#f8f9ff] grow">
        {children}
        </div>
        <Footer></Footer>
        </body>
    </html>
  );
}
